version: 2

project_name: galaxy-store-cli

builds:
  - id: gsc
    main: .
    binary: gsc
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
      - -X main.commit={{ .ShortCommit }}
      - -X main.date={{ .CommitDate }}

archives:
  - id: gsc
    ids:
      - gsc
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      gsc_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - LICENSE
      - README.md

checksum:
  name_template: checksums.txt
  algorithm: sha256

sboms:
  - id: archives
    artifacts: archive

source:
  enabled: true
  name_template: galaxy-store-cli_{{ .Version }}_source

snapshot:
  version_template: snapshot-{{ .ShortCommit }}

changelog:
  use: git
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  draft: true
  replace_existing_draft: true
