package commanddocs

import (
	"flag"
	"io"
	"strings"
	"testing"

	"github.com/peterbourgon/ff/v3/ffcli"

	"github.com/rudrankriyam/Galaxy-Store-CLI/cmd"
)

func TestRenderIsDeterministicAndRecursive(t *testing.T) {
	flags := flag.NewFlagSet("child", flag.ContinueOnError)
	flags.String("z-last", "z", "Last flag")
	flags.String("a-first", "", "First flag with a | pipe")
	root := &ffcli.Command{
		Name:       "gsc",
		ShortUsage: "gsc <command> [flags]",
		ShortHelp:  "Root help.",
		Subcommands: []*ffcli.Command{
			{
				Name:       "parent",
				ShortUsage: "incorrect group usage",
				ShortHelp:  "Parent help.",
				Subcommands: []*ffcli.Command{
					{
						Name:       "child",
						ShortUsage: "gsc parent child [flags]",
						ShortHelp:  "Child help.",
						FlagSet:    flags,
					},
				},
			},
		},
	}

	first := Render(root)
	second := Render(root)
	if first != second {
		t.Fatal("rendered command reference changed between identical runs")
	}
	for _, want := range []string{
		"<!-- Code generated by make docs; DO NOT EDIT. -->",
		"## `gsc parent`",
		"gsc parent <command> [flags]",
		"## `gsc parent child`",
		"`--a-first string`",
		"First flag with a \\| pipe",
		"`--z-last string`",
	} {
		if !strings.Contains(first, want) {
			t.Errorf("reference missing %q:\n%s", want, first)
		}
	}
	if strings.Index(first, "--a-first") > strings.Index(first, "--z-last") {
		t.Fatalf("flags are not sorted deterministically:\n%s", first)
	}
}

func TestRenderCompleteCommandTreeDoesNotResolveCredentials(t *testing.T) {
	const accessTokenCanary = "command-docs-access-token-canary"
	const accountCanary = "command-docs-service-account-canary"
	configPathCanary := t.TempDir()
	t.Setenv("GSC_ACCESS_TOKEN", accessTokenCanary)
	t.Setenv("GSC_SERVICE_ACCOUNT_ID", accountCanary)
	t.Setenv("GSC_CONFIG_PATH", configPathCanary)

	root := cmd.RootCommand("documentation", io.Discard, io.Discard)
	reference := Render(root)

	for _, want := range []string{
		"## `gsc apps status update`",
		"## `gsc uploads sessions create`",
		"## `gsc iap subscriptions revoke`",
		"`--content-id string`",
		"`--private-key string`",
		"Examples:",
	} {
		if !strings.Contains(reference, want) {
			t.Errorf("reference missing %q", want)
		}
	}
	for _, secret := range []string{accessTokenCanary, accountCanary, configPathCanary} {
		if strings.Contains(reference, secret) {
			t.Errorf("reference contains local or secret value %q", secret)
		}
	}
}
