// Package commanddocs renders a deterministic reference from the in-process
// command tree. It does not execute commands or resolve local configuration.
package commanddocs

import (
	"flag"
	"fmt"
	"strings"

	"github.com/peterbourgon/ff/v3/ffcli"
)

const generatedNotice = "<!-- Code generated by make docs; DO NOT EDIT. -->"

// Render returns the complete Markdown command reference for root.
func Render(root *ffcli.Command) string {
	var document strings.Builder
	document.WriteString(generatedNotice)
	document.WriteString("\n\n# gsc command reference\n\n")
	document.WriteString(
		"This reference is generated from the command tree compiled into `gsc`. " +
			"Run `make docs` after changing commands or flags.\n",
	)
	renderCommand(&document, root, root.Name)
	return document.String()
}

func renderCommand(document *strings.Builder, command *ffcli.Command, path string) {
	fmt.Fprintf(document, "\n## `%s`\n\n", path)

	help := strings.TrimSpace(command.LongHelp)
	if help == "" {
		help = strings.TrimSpace(command.ShortHelp)
	}
	if help != "" {
		document.WriteString(help)
		document.WriteString("\n")
	}

	usage := command.ShortUsage
	if len(command.Subcommands) > 0 {
		usage = path + " <command> [flags]"
	}
	if usage != "" {
		document.WriteString("\n### Usage\n\n```text\n")
		document.WriteString(usage)
		document.WriteString("\n```\n")
	}

	if len(command.Subcommands) > 0 {
		document.WriteString("\n### Commands\n\n")
		document.WriteString("| Command | Description |\n")
		document.WriteString("| --- | --- |\n")
		for _, subcommand := range command.Subcommands {
			fmt.Fprintf(
				document,
				"| `%s %s` | %s |\n",
				path,
				subcommand.Name,
				escapeTableCell(subcommand.ShortHelp),
			)
		}
	}

	if command.FlagSet != nil {
		var flags []*flag.Flag
		command.FlagSet.VisitAll(func(flagValue *flag.Flag) {
			flags = append(flags, flagValue)
		})
		if len(flags) > 0 {
			document.WriteString("\n### Flags\n\n")
			document.WriteString("| Flag | Default | Description |\n")
			document.WriteString("| --- | --- | --- |\n")
			for _, flagValue := range flags {
				valueName, description := flag.UnquoteUsage(flagValue)
				flagName := "--" + flagValue.Name
				if valueName != "" {
					flagName += " " + valueName
				}
				fmt.Fprintf(
					document,
					"| `%s` | `%s` | %s |\n",
					escapeCode(flagName),
					escapeCode(flagValue.DefValue),
					escapeTableCell(description),
				)
			}
		}
	}

	for _, subcommand := range command.Subcommands {
		renderCommand(document, subcommand, path+" "+subcommand.Name)
	}
}

func escapeTableCell(value string) string {
	value = strings.ReplaceAll(value, "\\", "\\\\")
	value = strings.ReplaceAll(value, "|", "\\|")
	value = strings.ReplaceAll(value, "\n", "<br>")
	return value
}

func escapeCode(value string) string {
	return strings.ReplaceAll(value, "`", "&#96;")
}
